### Delivery Service HTTP Requests

@host = http://localhost:8081

### Health check
GET {{host}}/actuator/health

### Metrics
GET {{host}}/actuator/metrics

### Get Delivery
GET {{host}}/api/v1/delivery/ebc9d5a8-f37a-4919-a7d1-589cd2a3da1b
Content-Type: application/json

### Fulfill Delivery
POST {{host}}/api/v1/delivery/ebc9d5a8-f37a-4919-a7d1-589cd2a3da1b